### ISSUE TITLE
what even is this?

### ISSUE THREAD

**Issue by enaisnotanumber** [kentjhall/horizon-linux#7]
the readme and description are quite vague, it makes it very hard to see the actual intended use case of this

**Comment by julianbraha** [comment]
Unfortunately, the reddit post explaining what this is was deleted, but you can still access it from the archives:
1. Initial introduction: 
https://web.archive.org/web/20220911233938/https://www.reddit.com/r/linux_gaming/comments/wnuh3u/introducing_horizon_linux/
2. Update description: 
https://web.archive.org/web/20220914193035/https://www.reddit.com/r/emulation/comments/xadhj4/horizon_linux_progress_update_9922/

**Comment by fluffykanade** [comment]
wow, this is actually really cool
